

//-----------------------------------------------
// UNIVERSIDAD DEL VALLE DE GUATEMALA
// IE2023: PROGRAMACION DE MICROCONTROLADORES
// PRELAB6.c
// AUTOR: ANTHONY ALEJANDRO BOTEO LÓPEZ
// PROYECTO: PRELABORATORIO 
// HARDWARE: ATMEGA328P
// CREADO: 4/25/2025 4:57:32 PM
// ULTIMA MODIFICACION: 4/25/2025
// DESCRIPCIÓN:
//-----------------------------------------------
#include "UART/CONF_UART.h"

int main() {
	UART_conf();
	ADC_conf();
	LED_conf();

	uint8_t GUARDAR_VALOR = 0;
	uint32_t CONTADOR2 = 0;    //ULTIMO TIEMPO ENVIADO


	
	CADENA("Ya no hay más labs maldita sea\n");

	while (1) {
		_delay_ms(1);
		COUNTER++;

		//LEER VALOR DEL ADC
		VALOR_ADC = LEER_ADC();

		//DATO EVIADO = 1, MOSTRARLO EN LEDS
		if (DATO_ENVIADO) {
			GUARDAR_VALOR = DATO_RECIBIDO;    //GUARDAMOS EL DATO RECIBIDO
			ENVIAR_UART(DATO_RECIBIDO);        //DEVOLVEMOS EL DATO PARA MOSTRARLO EN TERMINAL
			ENVIAR_UART('\n');                //SALTO PARA VERSE MAS CUTE
			DATO_ENVIADO = 0;    //YA FUE PROCESADO EL DATO
		}

		//NO FUNCIONA CON ESTO, SI MOSTRAMOS TAMBIEN EL VALOR DEL ADC EN LOS LEDS
		// GUARDAR_VALOR = VALOR_ADC >> 2;

		MOSTRAR_LED(GUARDAR_VALOR);

		//MOSTRAR EN DISPLAY LUEGO DE 500MS LUEGO DE ENVIAR EN ADC
		if (COUNTER - CONTADOR2 >= 500) {
			char buffer[10];
			sprintf(buffer, "ADC: %u\n", VALOR_ADC); // "u" VALOR DECIMAL, "X" hexa y .2fV voltaje
			CADENA(buffer);
			CONTADOR2 = COUNTER;
		}
	}
}